/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle push events
self.addEventListener('push', (event) => {
  console.log('[SW] Push received:', event);
  
  let data: {
    title?: string;
    body?: string;
    icon?: string;
    badge?: string;
    dir?: 'rtl' | 'ltr';
    lang?: string;
    tag?: string;
    url?: string;
    child_name?: string;
  } = {};
  
  try {
    if (event.data) {
      data = event.data.json();
    }
  } catch (e) {
    console.error('[SW] Error parsing push data:', e);
    data = { title: 'Kippy', body: event.data?.text() || 'התראה חדשה' };
  }
  
  const title = data.title || 'Kippy';
  
  event.waitUntil(
    self.registration.showNotification(title, {
      body: data.body || 'נמצא תוכן שדורש את תשומת לבך',
      icon: data.icon || '/pwa-192x192.png',
      badge: data.badge || '/pwa-192x192.png',
      dir: data.dir || 'rtl',
      lang: data.lang || 'he',
      tag: data.tag || 'kippy-notification',
      data: { 
        url: data.url || '/alerts',
        child_name: data.child_name 
      },
      requireInteraction: true,
    })
  );
});

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  console.log('[SW] Notification click:', event.action);
  
  event.notification.close();
  
  // If user clicked dismiss, do nothing
  if (event.action === 'dismiss') {
    return;
  }
  
  // Get the URL to open
  const url = event.notification.data?.url || '/alerts';
  
  // Open the app or focus existing window
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        // Check if there's already a window open
        for (const client of clientList) {
          if (client.url.includes(self.registration.scope) && 'focus' in client) {
            client.focus();
            // Navigate to the alert URL
            if ('navigate' in client) {
              (client as WindowClient).navigate(url);
            }
            return;
          }
        }
        // If no window is open, open a new one
        if (self.clients.openWindow) {
          return self.clients.openWindow(url);
        }
      })
  );
});

// Handle push subscription change
self.addEventListener('pushsubscriptionchange', (event) => {
  console.log('[SW] Push subscription changed');
  // The frontend will handle re-subscribing when the user opens the app
});
