/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Handle skip waiting message from the app
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle push events
self.addEventListener('push', (event) => {
  console.log('[SW] Push received:', event);
  
  let data: {
    title?: string;
    body?: string;
    icon?: string;
    badge?: string;
    dir?: 'rtl' | 'ltr';
    lang?: string;
    tag?: string;
    url?: string;
    child_name?: string;
  } = {};
  
  try {
    if (event.data) {
      data = event.data.json();
    }
  } catch (e) {
    console.error('[SW] Error parsing push data:', e);
    data = { title: 'Kippy', body: event.data?.text() || 'התראה חדשה' };
  }
  
  const title = data.title || 'Kippy';
  
  event.waitUntil(
    self.registration.showNotification(title, {
      body: data.body || 'נמצא תוכן שדורש את תשומת לבך',
      icon: data.icon || '/pwa-192x192.png',
      badge: data.badge || '/pwa-192x192.png',
      dir: data.dir || 'rtl',
      lang: data.lang || 'he',
      tag: data.tag || 'kippy-notification',
      data: { 
        url: data.url || '/alerts',
        child_name: data.child_name 
      },
      requireInteraction: true,
    })
  );
});

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  console.log('[SW] Notification click:', event.action);
  
  event.notification.close();
  
  // If user clicked dismiss, do nothing
  if (event.action === 'dismiss') {
    return;
  }
  
  // Get the relative URL path from notification data
  const urlPath = event.notification.data?.url || '/alerts';
  
  // Build full URL within the PWA scope - this helps open in the installed app
  const scope = self.registration.scope;
  const fullUrl = new URL(urlPath, scope).href;
  
  console.log('[SW] Opening URL:', fullUrl);
  
  // Open the app or focus existing window
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        // First, try to find an existing PWA window and focus it
        for (const client of clientList) {
          // Check if this client is within our app's scope
          if (client.url.startsWith(scope) && 'focus' in client) {
            console.log('[SW] Found existing window, focusing and navigating');
            return client.focus().then((focusedClient) => {
              // Navigate to the alert URL within the existing window
              if (focusedClient && 'navigate' in focusedClient) {
                return (focusedClient as WindowClient).navigate(fullUrl);
              }
            });
          }
        }
        
        // No existing window found - open a new one
        // Using the full URL within scope helps browsers open the installed PWA
        console.log('[SW] No existing window, opening new one');
        if (self.clients.openWindow) {
          return self.clients.openWindow(fullUrl);
        }
      })
  );
});

// Handle push subscription change
self.addEventListener('pushsubscriptionchange', (event) => {
  console.log('[SW] Push subscription changed');
  // The frontend will handle re-subscribing when the user opens the app
});
