-- Add new AI output columns for enhanced alert card design
ALTER TABLE public.alerts ADD COLUMN IF NOT EXISTS ai_title TEXT;
ALTER TABLE public.alerts ADD COLUMN IF NOT EXISTS ai_context TEXT;
ALTER TABLE public.alerts ADD COLUMN IF NOT EXISTS ai_meaning TEXT;
ALTER TABLE public.alerts ADD COLUMN IF NOT EXISTS ai_social_context JSONB;

-- Add comments for documentation
COMMENT ON COLUMN public.alerts.ai_title IS 'Dynamic title generated by AI (e.g., "שיחה פרטית עם נועם")';
COMMENT ON COLUMN public.alerts.ai_context IS 'General context about the situation (2-3 sentences)';
COMMENT ON COLUMN public.alerts.ai_meaning IS 'What this means for the parent (1 sentence)';
COMMENT ON COLUMN public.alerts.ai_social_context IS 'JSON with social context for group chats: {label, participants, description}';